# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recent, stable version of pre-commit-hooks
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json # Good for package.json, etc.
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0 # Corresponds to Prettier v3.1.0, compatible with Prettier 3.x
    hooks:
    -   id: prettier
        files: \.(js|json|html|css|md)$
        # This hook should respect local .prettierrc or package.json prettier config
